### PR TITLE
Rails 7.2 support

### PR DESCRIPTION
**Pull request by hatajoe**
I added Rails 7.2 support based on https://github.com/iMacTia/lograge-sql/pull/51 .
I'm not sure for whether some additional changes are needed or not. Can you please provide a review?
Thank you.

### CODE REVIEW

**Comment by gemitoytp** [comment]
When would it be released to support Rails 7.2?

**Comment by iMacTia** [comment]
I'm so sorry everyone, I went on holiday for a few weeks and still catching up with the backlog I found when I came back 😭
Let's see if this just passes and then I can cut a new release

**Review by iMacTia — APPROVED** [review]
Thank you for nudging me on this, looks good.
Merging and releasing soon 🎉

**Comment by gemitoytp** [comment]
Thanks @iMacTia !!! 🙌

**Pull request merged**
